AllCops:
  DisplayCopNames: true
  Exclude:
    - Gemfile
    - Rakefile
    - bin/*
    - vendor/**/*
    - tmp/**/*
    - scripts/*

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Enabled: false
  Max: 100
