dist: xenial
language: node_js
node_js:
  - 10.15.0
services:
  - postgresql
notifications:
  email: false
before_script:
  - rvm install 2.5.3
  - gem update --system
  - gem install bundler
  - bundle install --jobs=3 --retry=3
  - yarn
  - cp config/database.yml.ci config/database.yml
  - bundle exec rails db:create db:migrate
script: bundle exec rspec
