language: ruby
services:
  - postgresql
rvm:
  - 2.5
notifications:
  email: false
before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:create db:migrate
script: bundle exec rspec
