language: ruby
services:
  - postgresql
rvm:
  - 2.5
notifications:
  email: false
before_script:
  - nvm install 10.15.1
  - yarn
  - cp config/database.yml.ci config/database.yml
  - bundle exec rails db:create db:migrate
script: bundle exec rspec
