dist: xenial
language: ruby
services:
  - postgresql
rvm:
  - 2.5
notifications:
  email: false
before_script:
  - gem update --system
  - gem install bundler
  - nvm install 10.15.1
  - sudo apt-get update && sudo apt-get install --no-install-recommends yarn
  - yarn
  - cp config/database.yml.ci config/database.yml
  - bundle exec rails db:create db:migrate
script: bundle exec rspec
