apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Chart.Name }}-config"
  namespace: "{{ .Release.Namespace }}"
data:
  AWS_ACCESS_KEY_ID: "{{ .Values.config.awsAccessKeyId }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.config.awsSecretAccessKey }}"
  DATABASE_URL: "{{ .Values.config.databaseUrl }}"
  OLD_DATABASE_URL: "{{ .Values.config.oldDatabaseUrl }}"
  IMGPROXY_KEY: "{{ .Values.config.imgproxyKey }}"
  IMGPROXY_SALT: "{{ .Values.config.imgproxySalt }}"
  IMGPROXY_ENDPOINT: "{{ .Values.config.imgproxyEndpoint }}"
  IMGPROXY_S3_ENDPOINT: "{{ .Values.config.s3Host }}"
  IMGPROXY_USE_S3: "true"
  DOMAIN_NAME: "{{ .Values.config.domainName }}"
  RAILS_ENV: "production"
  RAILS_SERVE_STATIC_FILES: "true"
  RAILS_LOG_TO_STDOUT: "true"
  FORCE_SSL: "true"
  REDIS_URL: "{{ .Values.config.redisUrl }}"
  {{- if .Values.config.s3Host }}
  S3_HOST: "{{ .Values.config.s3Host }}"
  {{- end }}
  S3_REGION: "us-east-1"
  SECRET_KEY_BASE: "{{ .Values.config.secretKeyBase }}"
  RUBY_YJIT_ENABLE: "true"
  SMTP_HOST: "{{ .Values.config.smtpHost }}"
  SMTP_PORT: "{{ .Values.config.smtpPort }}"
  SMTP_USER: "{{ .Values.config.smtpUser }}"
  SMTP_PASSWORD: "{{ .Values.config.smtpPassword }}"
  MEILISEARCH_HOST: "{{ .Values.config.meilisearchHost }}"
