name: Ruby workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mds_test
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        # Docker Hub image
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      minio:
        image: lazybit/minio
        ports:
          - 9000:9000
        env:
          MINIO_ACCESS_KEY: minioadmin1
          MINIO_SECRET_KEY: minioadmin1
        # volumes:
        #   - ${{ github.workspace }}/data:/data
        options: --name=minio --health-cmd "curl http://localhost:9000/minio/health/live"

    env:
      RAILS_ENV: test
      GEMFILE_RUBY_VERSION: 3.2.2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mds_test
      PGHOST: localhost
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/mds_test"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.9
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install js deps
        run: yarn install --frozen-lockfile

      - name: Copy test env
        run: cp .env.ci .env

      - name: Create DB
        run: bin/rails db:prepare

      - name: Run tests
        run: bundle exec rspec

      - name: Run standardrb
        run: bundle exec standardrb

      - name: Run bundle audit
        run: |
          gem install bundle-audit
          bundle-audit
